In [1]:
# import necessary libraries
import pandas as pd
import csv
from os import listdir
pd.options.mode.chained_assignment = None  # default='warn'
from sklearn import preprocessing
import numpy as np

In [2]:
# Read the preprocessed csv file
preprocessed_data = pd.read_csv('C:/Users/nandh/OneDrive/Desktop/IndependantStudy/temp1/preprocessed_Train.csv', sep = ',')
preprocessed_data

HR      O2Sat       Temp        SBP        MAP        DBP  \
0       30.426709  29.971916  28.459116  28.756207  29.216997   0.000000   
1       30.542510  29.971916  28.668050  29.142885  29.480110   0.000000   
2       30.310908  29.624905  28.668050  28.928064  28.730876   0.000000   
3       30.253007  29.624905  28.668050  28.025814  28.427050   0.000000   
4       30.079305  28.930884  28.668050  28.498421  28.730876   0.000000   
...           ...        ...        ...        ...        ...        ...   
383319  28.747590  28.583873  28.250182  28.627314  29.277762  29.077440   
383320  28.400186  28.930884  28.250182  28.584349  29.034701  29.219464   
383321  28.631789  29.277895  28.250182  28.412492  29.034701  29.361489   
383322  28.863391  29.624905  28.511350  29.013992  29.520822  29.503514   
383323  28.747590  28.930884  28.511350  28.885099  29.885413  29.645539   

             Resp  BaseExcess       FiO2         pH  ...        WBC  \
0       28.963045    0.000000  28.340699   0.000000  ...   0.000000   
1       33.797738   29.183506  28.340699  28.489274  ...   0.000000   
2       33.797738   29.183506  28.340699  28.489274  ...   0.000000   
3       33.797738   29.183506  28.340699  28.489274  ...   0.000000   
4       33.797738   29.183506  28.340699  28.489274  ...   0.000000   
...           ...         ...        ...        ...  ...        ...   
383319  28.272374    0.000000   0.000000   0.000000  ...  28.087024   
383320  28.272374    0.000000   0.000000   0.000000  ...  28.087024   
383321  28.272374    0.000000   0.000000   0.000000  ...  28.087024   
383322  28.469709    0.000000   0.000000   0.000000  ...  28.087024   
383323  28.272374    0.000000   0.000000   0.000000  ...  28.087024   

        Platelets        Age     Gender  HospAdmTime  Patient_id  SepsisLabel  \
0        0.000000  28.400245  29.889090    29.377185   27.272181            0   
1        0.000000  28.400245  29.889090    29.377185   27.272181            0   
2        0.000000  28.400245  29.889090    29.377185   27.272181            0   
3        0.000000  28.400245  29.889090    29.377185   27.272181            0   
4        0.000000  28.400245  29.889090    29.377185   27.272181            0   
...           ...        ...        ...          ...         ...          ...   
383319  29.197972  29.004876  27.875254    29.377396   30.731663            0   
383320  29.197972  29.004876  27.875254    29.377396   30.731663            0   
383321  29.197972  29.004876  27.875254    29.377396   30.731663            0   
383322  29.197972  29.004876  27.875254    29.377396   30.731663            0   
383323  29.197972  29.004876  27.875254    29.377396   30.731663            0   

        Sepsis_Shift1  Sepsis_Shift6  Sepsis_Shift12  
0                   0              0               0  
1                   0              0               0  
2                   0              0               0  
3                   0              0               0  
4                   0              0               0  
...               ...            ...             ...  
383319              0              0               0  
383320              0              0               0  
383321              0              0               0  
383322              0              0               0  
383323              0              0               0  

[383324 rows x 29 columns]

In [3]:
#Drop the preodicting column to train the data
X = preprocessed_data.drop('Patient_id', axis=1)
X = X.drop('SepsisLabel', axis=1)
X = X.drop('Sepsis_Shift1', axis=1)
X = X.drop('Sepsis_Shift6', axis=1)
X = X.drop('Sepsis_Shift12', axis=1)
X

HR      O2Sat       Temp        SBP        MAP        DBP  \
0       30.426709  29.971916  28.459116  28.756207  29.216997   0.000000   
1       30.542510  29.971916  28.668050  29.142885  29.480110   0.000000   
2       30.310908  29.624905  28.668050  28.928064  28.730876   0.000000   
3       30.253007  29.624905  28.668050  28.025814  28.427050   0.000000   
4       30.079305  28.930884  28.668050  28.498421  28.730876   0.000000   
...           ...        ...        ...        ...        ...        ...   
383319  28.747590  28.583873  28.250182  28.627314  29.277762  29.077440   
383320  28.400186  28.930884  28.250182  28.584349  29.034701  29.219464   
383321  28.631789  29.277895  28.250182  28.412492  29.034701  29.361489   
383322  28.863391  29.624905  28.511350  29.013992  29.520822  29.503514   
383323  28.747590  28.930884  28.511350  28.885099  29.885413  29.645539   

             Resp  BaseExcess       FiO2         pH  ...    Glucose  \
0       28.963045    0.000000  28.340699   0.000000  ...   0.000000   
1       33.797738   29.183506  28.340699  28.489274  ...   0.000000   
2       33.797738   29.183506  28.340699  28.489274  ...   0.000000   
3       33.797738   29.183506  28.340699  28.489274  ...   0.000000   
4       33.797738   29.183506  28.340699  28.489274  ...   0.000000   
...           ...         ...        ...        ...  ...        ...   
383319  28.272374    0.000000   0.000000   0.000000  ...  30.994003   
383320  28.272374    0.000000   0.000000   0.000000  ...  30.994003   
383321  28.272374    0.000000   0.000000   0.000000  ...  30.994003   
383322  28.469709    0.000000   0.000000   0.000000  ...  31.052487   
383323  28.272374    0.000000   0.000000   0.000000  ...  31.052487   

        Magnesium  Potassium        Hct        Hgb        WBC  Platelets  \
0        0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
1        0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
2        0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
3        0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
4        0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
...           ...        ...        ...        ...        ...        ...   
383319  29.371945  28.172881  30.135562  29.584243  28.087024  29.197972   
383320  29.371945  28.172881  30.135562  29.584243  28.087024  29.197972   
383321  29.371945  28.172881  30.135562  29.584243  28.087024  29.197972   
383322  29.371945  28.172881  30.135562  29.584243  28.087024  29.197972   
383323  29.371945  28.172881  30.135562  29.584243  28.087024  29.197972   

              Age     Gender  HospAdmTime  
0       28.400245  29.889090    29.377185  
1       28.400245  29.889090    29.377185  
2       28.400245  29.889090    29.377185  
3       28.400245  29.889090    29.377185  
4       28.400245  29.889090    29.377185  
...           ...        ...          ...  
383319  29.004876  27.875254    29.377396  
383320  29.004876  27.875254    29.377396  
383321  29.004876  27.875254    29.377396  
383322  29.004876  27.875254    29.377396  
383323  29.004876  27.875254    29.377396  

[383324 rows x 24 columns]

In [4]:
y = preprocessed_data['SepsisLabel']
y

0         0
1         0
2         0
3         0
4         0
         ..
383319    0
383320    0
383321    0
383322    0
383323    0
Name: SepsisLabel, Length: 383324, dtype: int64

In [5]:
y_Shift1 = preprocessed_data['Sepsis_Shift1']
y_Shift1

0         0
1         0
2         0
3         0
4         0
         ..
383319    0
383320    0
383321    0
383322    0
383323    0
Name: Sepsis_Shift1, Length: 383324, dtype: int64

In [6]:
y_Shift6 = preprocessed_data['Sepsis_Shift6']
y_Shift6

0         0
1         0
2         0
3         0
4         0
         ..
383319    0
383320    0
383321    0
383322    0
383323    0
Name: Sepsis_Shift6, Length: 383324, dtype: int64

In [7]:
y_Shift12 = preprocessed_data['Sepsis_Shift12']
y_Shift12

0         0
1         0
2         0
3         0
4         0
         ..
383319    0
383320    0
383321    0
383322    0
383323    0
Name: Sepsis_Shift12, Length: 383324, dtype: int64

In [8]:
#Splitting train and test data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state= 109)

#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = gnb.predict(X_test)
#y_pred

In [9]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
#print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred) * 100))
confusionMatrix = confusion_matrix(y_test, y_pred,labels=[0, 1])
print("\nConfusion Matrix:\n", confusionMatrix)

Accuracy: 80.44%

F1 Score: 7.04

Confusion Matrix:
 [[91654 21335]
 [ 1157   852]]


In [10]:
TN = confusionMatrix[0,0]
TP = confusionMatrix[0,1]
FN = confusionMatrix[1,0]
FP = confusionMatrix[1,1]
print(TP,TN,FP,FN)
sensitivity = TP/(TP+FN)
print('Sensitivity : ', sensitivity )
specificity = TN/(TN+FP)
print('Specificity : ', specificity)

21335 91654 852 1157
Sensitivity :  0.9485594878178908
Specificity :  0.9907897866084362


In [11]:
#SMOTE

from imblearn.over_sampling import SMOTE
print("Before OverSampling, counts of label '1': {}".format(sum(y_train==1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train==0)))

sm = SMOTE(random_state=2)
X_train_res, y_train_res = sm.fit_sample(X_train, y_train.ravel())

print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_train_res==1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res==0)))

Before OverSampling, counts of label '1': 4801
Before OverSampling, counts of label '0': 263525 

After OverSampling, the shape of train_X: (527050, 24)
After OverSampling, the shape of train_y: (527050,) 

After OverSampling, counts of label '1': 263525
After OverSampling, counts of label '0': 263525


In [12]:
nb = GaussianNB()
nb.fit(X_train_res, y_train_res)
y_pred_smote = nb.predict(X_test)

In [13]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
#print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred_smote) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred_smote) * 100))
confusionMatrix = confusion_matrix(y_test, y_pred_smote,labels=[0, 1])
print("\nConfusion Matrix:\n", confusionMatrix)

Accuracy: 32.19%

F1 Score: 4.01

Confusion Matrix:
 [[35386 77603]
 [  380  1629]]


In [14]:
TN = confusionMatrix[0,0]
TP = confusionMatrix[0,1]
FN = confusionMatrix[1,0]
FP = confusionMatrix[1,1]
#print(TP,TN,FP,FN)
sensitivity = TP/(TP+FN)
print('Sensitivity : ', sensitivity )
specificity = TN/(TN+FP)
print('Specificity : ', specificity)

Sensitivity :  0.99512714309529
Specificity :  0.9559908145346481


In [15]:
#1 hour shift
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y_Shift1, test_size=0.3, random_state= 109)

#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = gnb.predict(X_test)
#y_pred

In [16]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
#print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred) * 100))
confusionMatrix = confusion_matrix(y_test, y_pred,labels=[0, 1])
print("\nConfusion Matrix:\n", confusionMatrix)

Accuracy: 80.57%

F1 Score: 7.45

Confusion Matrix:
 [[91755 21084]
 [ 1260   899]]


In [17]:
TN = confusionMatrix[0,0]
TP = confusionMatrix[0,1]
FN = confusionMatrix[1,0]
FP = confusionMatrix[1,1]
#print(TP,TN,FP,FN)
sensitivity = TP/(TP+FN)
print('Sensitivity : ', sensitivity )
specificity = TN/(TN+FP)
print('Specificity : ', specificity)

Sensitivity :  0.943609022556391
Specificity :  0.9902972348738317


In [18]:
#SMOTE

from imblearn.over_sampling import SMOTE
print("Before OverSampling, counts of label '1': {}".format(sum(y_train==1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train==0)))

sm = SMOTE(random_state=2)
X_train_res, y_train_res = sm.fit_sample(X_train, y_train.ravel())

print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_train_res==1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res==0)))

Before OverSampling, counts of label '1': 5262
Before OverSampling, counts of label '0': 263064 

After OverSampling, the shape of train_X: (526128, 24)
After OverSampling, the shape of train_y: (526128,) 

After OverSampling, counts of label '1': 263064
After OverSampling, counts of label '0': 263064


In [19]:
nb = GaussianNB()
nb.fit(X_train_res, y_train_res)
y_pred_smote = nb.predict(X_test)

In [20]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
#print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred_smote) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred_smote) * 100))
confusionMatrix = confusion_matrix(y_test, y_pred_smote,labels=[0, 1])
print("\nConfusion Matrix:\n", confusionMatrix)

Accuracy: 40.43%

F1 Score: 4.73

Confusion Matrix:
 [[44796 68043]
 [  457  1702]]


In [21]:
TN = confusionMatrix[0,0]
TP = confusionMatrix[0,1]
FN = confusionMatrix[1,0]
FP = confusionMatrix[1,1]
#print(TP,TN,FP,FN)
sensitivity = TP/(TP+FN)
print('Sensitivity : ', sensitivity )
specificity = TN/(TN+FP)
print('Specificity : ', specificity)

Sensitivity :  0.9933284671532847
Specificity :  0.9633962751086068


In [22]:
#6 hour shift
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y_Shift6, test_size=0.3, random_state= 109)

#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = gnb.predict(X_test)
#y_pred

In [23]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
#print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred) * 100))
confusionMatrix = confusion_matrix(y_test, y_pred,labels=[0, 1])
print("\nConfusion Matrix:\n", confusionMatrix)

Accuracy: 75.34%

F1 Score: 10.06

Confusion Matrix:
 [[85059 26915]
 [ 1438  1586]]


In [24]:
TN = confusionMatrix[0,0]
TP = confusionMatrix[0,1]
FN = confusionMatrix[1,0]
FP = confusionMatrix[1,1]
print(TP,TN,FP,FN)
sensitivity = TP/(TP+FN)
print('Sensitivity : ', sensitivity )
specificity = TN/(TN+FP)
print('Specificity : ', specificity)

26915 85059 1586 1438
Sensitivity :  0.9492822628998695
Specificity :  0.981695423855964


In [25]:
#SMOTE

from imblearn.over_sampling import SMOTE
print("Before OverSampling, counts of label '1': {}".format(sum(y_train==1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train==0)))

sm = SMOTE(random_state=2)
X_train_res, y_train_res = sm.fit_sample(X_train, y_train.ravel())

print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_train_res==1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res==0)))

Before OverSampling, counts of label '1': 7270
Before OverSampling, counts of label '0': 261056 

After OverSampling, the shape of train_X: (522112, 24)
After OverSampling, the shape of train_y: (522112,) 

After OverSampling, counts of label '1': 261056
After OverSampling, counts of label '0': 261056


In [26]:
nb = GaussianNB()
nb.fit(X_train_res, y_train_res)
y_pred_smote = nb.predict(X_test)

In [27]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
#print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred_smote) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred_smote) * 100))
confusionMatrix = confusion_matrix(y_test, y_pred_smote,labels=[0, 1])
print("\nConfusion Matrix:\n", confusionMatrix)

Accuracy: 34.51%

F1 Score: 6.14

Confusion Matrix:
 [[37220 74754]
 [  562  2462]]


In [28]:
TN = confusionMatrix[0,0]
TP = confusionMatrix[0,1]
FN = confusionMatrix[1,0]
FP = confusionMatrix[1,1]
print(TP,TN,FP,FN)
sensitivity = TP/(TP+FN)
print('Sensitivity : ', sensitivity )
specificity = TN/(TN+FP)
print('Specificity : ', specificity)

74754 37220 2462 562
Sensitivity :  0.9925381061129109
Specificity :  0.9379567562118845


In [29]:
#12 hour shift
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y_Shift12, test_size=0.3, random_state= 109)

#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = gnb.predict(X_test)
#y_pred

In [30]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
#print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred) * 100))
confusionMatrix = confusion_matrix(y_test, y_pred,labels=[0, 1])
print("\nConfusion Matrix:\n", confusionMatrix)

Accuracy: 61.75%

F1 Score: 10.65

Confusion Matrix:
 [[68383 43019]
 [  973  2623]]


In [31]:
TN = confusionMatrix[0,0]
TP = confusionMatrix[0,1]
FN = confusionMatrix[1,0]
FP = confusionMatrix[1,1]
print(TP,TN,FP,FN)
sensitivity = TP/(TP+FN)
print('Sensitivity : ', sensitivity )
specificity = TN/(TN+FP)
print('Specificity : ', specificity)

43019 68383 2623 973
Sensitivity :  0.9778823422440444
Specificity :  0.9630594597639636


In [32]:
from imblearn.over_sampling import SMOTE
print("Before OverSampling, counts of label '1': {}".format(sum(y_train==1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train==0)))

sm = SMOTE(random_state=2)
X_train_res, y_train_res = sm.fit_sample(X_train, y_train.ravel())

print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_train_res==1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res==0)))

Before OverSampling, counts of label '1': 8606
Before OverSampling, counts of label '0': 259720 

After OverSampling, the shape of train_X: (519440, 24)
After OverSampling, the shape of train_y: (519440,) 

After OverSampling, counts of label '1': 259720
After OverSampling, counts of label '0': 259720


In [33]:
nb = GaussianNB()
nb.fit(X_train_res, y_train_res)

GaussianNB(priors=None, var_smoothing=1e-09)

In [34]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred) * 100))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 61.75%

F1 Score: 10.65

Confusion Matrix:
 [[68383 43019]
 [  973  2623]]


In [35]:
TN = confusionMatrix[0,0]
TP = confusionMatrix[0,1]
FN = confusionMatrix[1,0]
FP = confusionMatrix[1,1]
print(TP,TN,FP,FN)
sensitivity = TP/(TP+FN)
print('Sensitivity : ', sensitivity )
specificity = TN/(TN+FP)
print('Specificity : ', specificity)

43019 68383 2623 973
Sensitivity :  0.9778823422440444
Specificity :  0.9630594597639636
