In [1]:
# Import the necessary libraries
import pandas as pd
import csv
from os import listdir
pd.options.mode.chained_assignment = None  # default='warn'
from sklearn import preprocessing
import numpy as np

In [2]:
# Read the preprocessed file
preprocessed_data = pd.read_csv('C:/Users/nandh/OneDrive/Desktop/IndependantStudy/temp1/preprocessed_Train.csv', sep = ',')
preprocessed_data

HR      O2Sat       Temp        SBP        MAP        DBP  \
0       30.426709  29.971916  28.459116  28.756207  29.216997   0.000000   
1       30.542510  29.971916  28.668050  29.142885  29.480110   0.000000   
2       30.310908  29.624905  28.668050  28.928064  28.730876   0.000000   
3       30.253007  29.624905  28.668050  28.025814  28.427050   0.000000   
4       30.079305  28.930884  28.668050  28.498421  28.730876   0.000000   
...           ...        ...        ...        ...        ...        ...   
383319  28.747590  28.583873  28.250182  28.627314  29.277762  29.077440   
383320  28.400186  28.930884  28.250182  28.584349  29.034701  29.219464   
383321  28.631789  29.277895  28.250182  28.412492  29.034701  29.361489   
383322  28.863391  29.624905  28.511350  29.013992  29.520822  29.503514   
383323  28.747590  28.930884  28.511350  28.885099  29.885413  29.645539   

             Resp  BaseExcess       FiO2         pH  ...        WBC  \
0       28.963045    0.000000  28.340699   0.000000  ...   0.000000   
1       33.797738   29.183506  28.340699  28.489274  ...   0.000000   
2       33.797738   29.183506  28.340699  28.489274  ...   0.000000   
3       33.797738   29.183506  28.340699  28.489274  ...   0.000000   
4       33.797738   29.183506  28.340699  28.489274  ...   0.000000   
...           ...         ...        ...        ...  ...        ...   
383319  28.272374    0.000000   0.000000   0.000000  ...  28.087024   
383320  28.272374    0.000000   0.000000   0.000000  ...  28.087024   
383321  28.272374    0.000000   0.000000   0.000000  ...  28.087024   
383322  28.469709    0.000000   0.000000   0.000000  ...  28.087024   
383323  28.272374    0.000000   0.000000   0.000000  ...  28.087024   

        Platelets        Age     Gender  HospAdmTime  Patient_id  SepsisLabel  \
0        0.000000  28.400245  29.889090    29.377185   27.272181            0   
1        0.000000  28.400245  29.889090    29.377185   27.272181            0   
2        0.000000  28.400245  29.889090    29.377185   27.272181            0   
3        0.000000  28.400245  29.889090    29.377185   27.272181            0   
4        0.000000  28.400245  29.889090    29.377185   27.272181            0   
...           ...        ...        ...          ...         ...          ...   
383319  29.197972  29.004876  27.875254    29.377396   30.731663            0   
383320  29.197972  29.004876  27.875254    29.377396   30.731663            0   
383321  29.197972  29.004876  27.875254    29.377396   30.731663            0   
383322  29.197972  29.004876  27.875254    29.377396   30.731663            0   
383323  29.197972  29.004876  27.875254    29.377396   30.731663            0   

        Sepsis_Shift1  Sepsis_Shift6  Sepsis_Shift12  
0                   0              0               0  
1                   0              0               0  
2                   0              0               0  
3                   0              0               0  
4                   0              0               0  
...               ...            ...             ...  
383319              0              0               0  
383320              0              0               0  
383321              0              0               0  
383322              0              0               0  
383323              0              0               0  

[383324 rows x 29 columns]

In [3]:
# Drop the predicting columns to train the data
X = preprocessed_data.drop('Patient_id', axis=1)
X = X.drop('SepsisLabel', axis=1)
X = X.drop('Sepsis_Shift1', axis=1)
X = X.drop('Sepsis_Shift6', axis=1)
X = X.drop('Sepsis_Shift12', axis=1)
X

HR      O2Sat       Temp        SBP        MAP        DBP  \
0       30.426709  29.971916  28.459116  28.756207  29.216997   0.000000   
1       30.542510  29.971916  28.668050  29.142885  29.480110   0.000000   
2       30.310908  29.624905  28.668050  28.928064  28.730876   0.000000   
3       30.253007  29.624905  28.668050  28.025814  28.427050   0.000000   
4       30.079305  28.930884  28.668050  28.498421  28.730876   0.000000   
...           ...        ...        ...        ...        ...        ...   
383319  28.747590  28.583873  28.250182  28.627314  29.277762  29.077440   
383320  28.400186  28.930884  28.250182  28.584349  29.034701  29.219464   
383321  28.631789  29.277895  28.250182  28.412492  29.034701  29.361489   
383322  28.863391  29.624905  28.511350  29.013992  29.520822  29.503514   
383323  28.747590  28.930884  28.511350  28.885099  29.885413  29.645539   

             Resp  BaseExcess       FiO2         pH  ...    Glucose  \
0       28.963045    0.000000  28.340699   0.000000  ...   0.000000   
1       33.797738   29.183506  28.340699  28.489274  ...   0.000000   
2       33.797738   29.183506  28.340699  28.489274  ...   0.000000   
3       33.797738   29.183506  28.340699  28.489274  ...   0.000000   
4       33.797738   29.183506  28.340699  28.489274  ...   0.000000   
...           ...         ...        ...        ...  ...        ...   
383319  28.272374    0.000000   0.000000   0.000000  ...  30.994003   
383320  28.272374    0.000000   0.000000   0.000000  ...  30.994003   
383321  28.272374    0.000000   0.000000   0.000000  ...  30.994003   
383322  28.469709    0.000000   0.000000   0.000000  ...  31.052487   
383323  28.272374    0.000000   0.000000   0.000000  ...  31.052487   

        Magnesium  Potassium        Hct        Hgb        WBC  Platelets  \
0        0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
1        0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
2        0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
3        0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
4        0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
...           ...        ...        ...        ...        ...        ...   
383319  29.371945  28.172881  30.135562  29.584243  28.087024  29.197972   
383320  29.371945  28.172881  30.135562  29.584243  28.087024  29.197972   
383321  29.371945  28.172881  30.135562  29.584243  28.087024  29.197972   
383322  29.371945  28.172881  30.135562  29.584243  28.087024  29.197972   
383323  29.371945  28.172881  30.135562  29.584243  28.087024  29.197972   

              Age     Gender  HospAdmTime  
0       28.400245  29.889090    29.377185  
1       28.400245  29.889090    29.377185  
2       28.400245  29.889090    29.377185  
3       28.400245  29.889090    29.377185  
4       28.400245  29.889090    29.377185  
...           ...        ...          ...  
383319  29.004876  27.875254    29.377396  
383320  29.004876  27.875254    29.377396  
383321  29.004876  27.875254    29.377396  
383322  29.004876  27.875254    29.377396  
383323  29.004876  27.875254    29.377396  

[383324 rows x 24 columns]

In [4]:
y = preprocessed_data['SepsisLabel']
y

0         0
1         0
2         0
3         0
4         0
         ..
383319    0
383320    0
383321    0
383322    0
383323    0
Name: SepsisLabel, Length: 383324, dtype: int64

In [5]:
y_Shift1 = preprocessed_data['Sepsis_Shift1']
y_Shift1

0         0
1         0
2         0
3         0
4         0
         ..
383319    0
383320    0
383321    0
383322    0
383323    0
Name: Sepsis_Shift1, Length: 383324, dtype: int64

In [6]:
y_Shift6 = preprocessed_data['Sepsis_Shift6']
y_Shift6

0         0
1         0
2         0
3         0
4         0
         ..
383319    0
383320    0
383321    0
383322    0
383323    0
Name: Sepsis_Shift6, Length: 383324, dtype: int64

In [7]:
y_Shift12 = preprocessed_data['Sepsis_Shift12']
y_Shift12

0         0
1         0
2         0
3         0
4         0
         ..
383319    0
383320    0
383321    0
383322    0
383323    0
Name: Sepsis_Shift12, Length: 383324, dtype: int64

In [8]:
#No Shift

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state= 109)

#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [10]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred) ))
confusionMatrix = confusion_matrix(y_test, y_pred,labels=[0, 1])
print("\nConfusion Matrix:\n", confusionMatrix)

Accuracy: 99.15%

F1 Score: 0.70

Confusion Matrix:
 [[112896     93]
 [   888   1121]]


In [11]:
TN = confusionMatrix[0,0]
TP = confusionMatrix[0,1]
FN = confusionMatrix[1,0]
FP = confusionMatrix[1,1]
print(TP,TN,FP,FN)
sensitivity = TP/(TP+FN)
print('Sensitivity : ', sensitivity )
specificity = TN/(TN+FP)
print('Specificity : ', specificity)

93 112896 1121 888
Sensitivity :  0.09480122324159021
Specificity :  0.9901681328222984


In [12]:
feature_importances = pd.DataFrame(clf.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance',ascending=False)
feature_importances

importance
Age            0.063719
Temp           0.062206
HospAdmTime    0.061854
HR             0.054055
Platelets      0.052206
SBP            0.050657
Glucose        0.049565
WBC            0.048774
MAP            0.046197
Hct            0.044806
Resp           0.042748
Creatinine     0.041866
BUN            0.041388
Hgb            0.039985
DBP            0.038455
Calcium        0.037446
Potassium      0.037131
PaCO2          0.033467
O2Sat          0.032689
pH             0.032636
Magnesium      0.032542
FiO2           0.023469
BaseExcess     0.023080
Gender         0.009060

In [13]:
#SMOTE
from imblearn.over_sampling import SMOTE
print("Before OverSampling, counts of label '1': {}".format(sum(y_train==1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train==0)))

sm = SMOTE(random_state=2)
X_train_res, y_train_res = sm.fit_sample(X_train, y_train.ravel())

print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_train_res==1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res==0)))

Before OverSampling, counts of label '1': 4801
Before OverSampling, counts of label '0': 263525 

After OverSampling, the shape of train_X: (527050, 24)
After OverSampling, the shape of train_y: (527050,) 

After OverSampling, counts of label '1': 263525
After OverSampling, counts of label '0': 263525


In [14]:
#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train_res,y_train_res)
y_pred_smote = clf.predict(X_test)

In [15]:
feature_importances = pd.DataFrame(clf.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance',ascending=False)
feature_importances

importance
HospAdmTime    0.064593
Temp           0.062315
Age            0.059206
Resp           0.052431
FiO2           0.050548
BUN            0.049067
O2Sat          0.045645
Calcium        0.045277
WBC            0.045232
HR             0.042063
Creatinine     0.041699
Platelets      0.041693
PaCO2          0.041464
pH             0.040411
Magnesium      0.039359
Hct            0.037479
Hgb            0.036704
Glucose        0.036636
Potassium      0.035107
DBP            0.031828
SBP            0.030655
BaseExcess     0.025520
MAP            0.024463
Gender         0.020604

In [16]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
#print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred_smote) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred_smote) ))
confusionMatrix = confusion_matrix(y_test, y_pred_smote,labels=[0, 1])
print("\nConfusion Matrix:\n", confusionMatrix)

Accuracy: 99.17%

F1 Score: 0.76

Confusion Matrix:
 [[112557    432]
 [   527   1482]]


In [17]:
TN = confusionMatrix[0,0]
TP = confusionMatrix[0,1]
FN = confusionMatrix[1,0]
FP = confusionMatrix[1,1]
#print(TP,TN,FP,FN)
sensitivity = TP/(TP+FN)
print('Sensitivity : ', sensitivity )
specificity = TN/(TN+FP)
print('Specificity : ', specificity)

Sensitivity :  0.4504692387904067
Specificity :  0.9870044458474733


In [18]:
#1 hour shift
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y_Shift1, test_size=0.3, random_state= 109)

#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [19]:
feature_importances = pd.DataFrame(clf.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance',ascending=False)
feature_importances

importance
Age            0.065164
HospAdmTime    0.063544
Temp           0.061547
Platelets      0.052758
HR             0.052111
WBC            0.049861
Glucose        0.049750
SBP            0.048621
Hct            0.046919
MAP            0.044527
Resp           0.042399
Creatinine     0.042373
BUN            0.041999
Hgb            0.040880
Calcium        0.038590
DBP            0.037312
Potassium      0.036540
Magnesium      0.033073
PaCO2          0.033032
pH             0.032654
O2Sat          0.031380
FiO2           0.022860
BaseExcess     0.022843
Gender         0.009265

In [20]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
#print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred) ))
confusionMatrix = confusion_matrix(y_test, y_pred,labels=[0, 1])
print("\nConfusion Matrix:\n", confusionMatrix)

Accuracy: 99.16%

F1 Score: 0.73

Confusion Matrix:
 [[112736    103]
 [   868   1291]]


In [21]:
TN = confusionMatrix[0,0]
TP = confusionMatrix[0,1]
FN = confusionMatrix[1,0]
FP = confusionMatrix[1,1]
#print(TP,TN,FP,FN)
sensitivity = TP/(TP+FN)
print('Sensitivity : ', sensitivity )
specificity = TN/(TN+FP)
print('Specificity : ', specificity)

Sensitivity :  0.10607621009268794
Specificity :  0.9886781200943636


In [22]:
#SMOTE

from imblearn.over_sampling import SMOTE
print("Before OverSampling, counts of label '1': {}".format(sum(y_train==1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train==0)))

sm = SMOTE(random_state=2)
X_train_res, y_train_res = sm.fit_sample(X_train, y_train.ravel())

print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_train_res==1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res==0)))

Before OverSampling, counts of label '1': 5262
Before OverSampling, counts of label '0': 263064 

After OverSampling, the shape of train_X: (526128, 24)
After OverSampling, the shape of train_y: (526128,) 

After OverSampling, counts of label '1': 263064
After OverSampling, counts of label '0': 263064


In [23]:
#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train_res,y_train_res)
y_pred_smote = clf.predict(X_test)

In [24]:
feature_importances = pd.DataFrame(clf.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance',ascending=False)
feature_importances

importance
HospAdmTime    0.066459
Age            0.061030
Temp           0.059567
Resp           0.056198
FiO2           0.049447
BUN            0.048389
WBC            0.046432
O2Sat          0.044054
Calcium        0.043669
pH             0.042856
Platelets      0.042039
Creatinine     0.042002
HR             0.041348
Magnesium      0.040277
PaCO2          0.039020
Hgb            0.037689
Hct            0.037482
Glucose        0.036723
Potassium      0.034553
SBP            0.030637
DBP            0.030037
BaseExcess     0.027223
MAP            0.024763
Gender         0.018105

In [25]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
#print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred_smote) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred_smote) ))
confusionMatrix = confusion_matrix(y_test, y_pred_smote,labels=[0, 1])
print("\nConfusion Matrix:\n", confusionMatrix)

Accuracy: 99.19%

F1 Score: 0.78

Confusion Matrix:
 [[112404    435]
 [   494   1665]]


In [26]:
TN = confusionMatrix[0,0]
TP = confusionMatrix[0,1]
FN = confusionMatrix[1,0]
FP = confusionMatrix[1,1]
#print(TP,TN,FP,FN)
sensitivity = TP/(TP+FN)
print('Sensitivity : ', sensitivity )
specificity = TN/(TN+FP)
print('Specificity : ', specificity)

Sensitivity :  0.4682454251883746
Specificity :  0.9854035715224996


In [27]:
#6 hour shift
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y_Shift6, test_size=0.3, random_state= 109)

#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [28]:
feature_importances = pd.DataFrame(clf.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance',ascending=False)
feature_importances

importance
Age            0.068318
HospAdmTime    0.067032
Temp           0.056435
Platelets      0.054027
WBC            0.052143
HR             0.049644
Glucose        0.049079
Hct            0.047168
SBP            0.045537
BUN            0.044762
Creatinine     0.044648
Hgb            0.043119
Calcium        0.041234
Resp           0.039822
MAP            0.039761
Potassium      0.036740
DBP            0.034864
PaCO2          0.033708
Magnesium      0.033151
pH             0.031460
O2Sat          0.028697
FiO2           0.025425
BaseExcess     0.023629
Gender         0.009596

In [29]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
#print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred) ))
confusionMatrix = confusion_matrix(y_test, y_pred,labels=[0, 1])
print("\nConfusion Matrix:\n", confusionMatrix)

Accuracy: 99.09%

F1 Score: 0.80

Confusion Matrix:
 [[111857    117]
 [   935   2089]]


In [30]:
TN = confusionMatrix[0,0]
TP = confusionMatrix[0,1]
FN = confusionMatrix[1,0]
FP = confusionMatrix[1,1]
#print(TP,TN,FP,FN)
sensitivity = TP/(TP+FN)
print('Sensitivity : ', sensitivity)
specificity = TN/(TN+FP)
print('Specificity : ', specificity)

Sensitivity :  0.1112167300380228
Specificity :  0.9816667544275358


In [31]:
#SMOTE

from imblearn.over_sampling import SMOTE
print("Before OverSampling, counts of label '1': {}".format(sum(y_train==1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train==0)))

sm = SMOTE(random_state=2)
X_train_res, y_train_res = sm.fit_sample(X_train, y_train.ravel())

print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_train_res==1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res==0)))

Before OverSampling, counts of label '1': 7270
Before OverSampling, counts of label '0': 261056 

After OverSampling, the shape of train_X: (522112, 24)
After OverSampling, the shape of train_y: (522112,) 

After OverSampling, counts of label '1': 261056
After OverSampling, counts of label '0': 261056


In [32]:
#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train_res,y_train_res)
y_pred_smote = clf.predict(X_test)

In [33]:
feature_importances = pd.DataFrame(clf.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance',ascending=False)
feature_importances

importance
HospAdmTime    0.070331
Age            0.064873
Temp           0.052222
BUN            0.049149
Resp           0.049029
FiO2           0.048850
WBC            0.048561
Calcium        0.048073
Platelets      0.044347
Creatinine     0.043913
pH             0.042679
O2Sat          0.041800
Magnesium      0.040196
HR             0.039813
Hgb            0.038874
PaCO2          0.038560
Glucose        0.037835
Hct            0.037833
Potassium      0.034932
SBP            0.030620
DBP            0.030263
BaseExcess     0.026829
MAP            0.022985
Gender         0.017436

In [34]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
#print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred_smote) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred_smote) ))
confusionMatrix = confusion_matrix(y_test, y_pred_smote,labels=[0, 1])
print("\nConfusion Matrix:\n", confusionMatrix)

Accuracy: 99.13%

F1 Score: 0.83

Confusion Matrix:
 [[111517    457]
 [   538   2486]]


In [35]:
TN = confusionMatrix[0,0]
TP = confusionMatrix[0,1]
FN = confusionMatrix[1,0]
FP = confusionMatrix[1,1]
#print(TP,TN,FP,FN)
sensitivity = TP/(TP+FN)
print('Sensitivity : ', sensitivity )
specificity = TN/(TN+FP)
print('Specificity : ', specificity)

Sensitivity :  0.4592964824120603
Specificity :  0.9781935563099217


In [36]:
#12 hour shift
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y_Shift12, test_size=0.3, random_state= 109)

#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [37]:
feature_importances = pd.DataFrame(clf.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance',ascending=False)
feature_importances

importance
Age            0.065657
HospAdmTime    0.064385
Platelets      0.057447
WBC            0.055507
Temp           0.050998
BUN            0.049408
Creatinine     0.049105
Hct            0.048910
Glucose        0.046769
Hgb            0.046425
HR             0.045301
Calcium        0.043311
SBP            0.042442
Potassium      0.038067
Magnesium      0.037209
Resp           0.036063
PaCO2          0.035634
MAP            0.034862
pH             0.033955
DBP            0.032661
FiO2           0.026267
O2Sat          0.025268
BaseExcess     0.024897
Gender         0.009453

In [38]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
#print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred) ))
confusionMatrix = confusion_matrix(y_test, y_pred,labels=[0, 1])
print("\nConfusion Matrix:\n", confusionMatrix)

Accuracy: 99.29%

F1 Score: 0.88

Confusion Matrix:
 [[111293    109]
 [   712   2884]]


In [39]:
TN = confusionMatrix[0,0]
TP = confusionMatrix[0,1]
FN = confusionMatrix[1,0]
FP = confusionMatrix[1,1]
#print(TP,TN,FP,FN)
sensitivity = TP/(TP+FN)
print('Sensitivity : ', sensitivity )
specificity = TN/(TN+FP)
print('Specificity : ', specificity)

Sensitivity :  0.13276492082825822
Specificity :  0.9747409723499479


In [40]:
#SMOTE

from imblearn.over_sampling import SMOTE
print("Before OverSampling, counts of label '1': {}".format(sum(y_train==1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train==0)))

sm = SMOTE(random_state=2)
X_train_res, y_train_res = sm.fit_sample(X_train, y_train.ravel())

print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_train_res==1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res==0)))

Before OverSampling, counts of label '1': 8606
Before OverSampling, counts of label '0': 259720 

After OverSampling, the shape of train_X: (519440, 24)
After OverSampling, the shape of train_y: (519440,) 

After OverSampling, counts of label '1': 259720
After OverSampling, counts of label '0': 259720


In [41]:
#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train_res,y_train_res)
y_pred_smote = clf.predict(X_test)

In [42]:
feature_importances = pd.DataFrame(clf.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance',ascending=False)
feature_importances

importance
HospAdmTime    0.068956
Age            0.065360
Calcium        0.055416
BUN            0.052076
WBC            0.050309
Magnesium      0.049356
pH             0.047135
PaCO2          0.046546
Temp           0.045987
Platelets      0.045955
Creatinine     0.044796
FiO2           0.042832
Hgb            0.041848
Resp           0.041544
Hct            0.040435
Glucose        0.036604
HR             0.036406
Potassium      0.035598
O2Sat          0.033779
BaseExcess     0.028031
DBP            0.027719
SBP            0.027291
MAP            0.021404
Gender         0.014618

In [43]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
#print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred_smote) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred_smote) ))
confusionMatrix = confusion_matrix(y_test, y_pred_smote,labels=[0, 1])
print("\nConfusion Matrix:\n", confusionMatrix)

Accuracy: 99.38%

F1 Score: 0.90

Confusion Matrix:
 [[111085    317]
 [   395   3201]]


In [44]:
TN = confusionMatrix[0,0]
TP = confusionMatrix[0,1]
FN = confusionMatrix[1,0]
FP = confusionMatrix[1,1]
#print(TP,TN,FP,FN)
sensitivity = TP/(TP+FN)
print('Sensitivity : ', sensitivity )
specificity = TN/(TN+FP)
print('Specificity : ', specificity)

Sensitivity :  0.4452247191011236
Specificity :  0.9719913200217
